# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provision :shell, path: "../provision.sh"
  config.vm.boot_timeout = 600

  config.ssh.forward_agent = true
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  # config.vm.network "forwarded_port", host: 5080, guest: 5000

  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true  # <-- set to true to not boot in headless mode (i.e. to have a gui)
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # machine for development work
  config.vm.define "bsp-precise-64-12.04-LTS" do
    config.vm.network "private_network", ip: "192.168.33.11"
  end
end
