#!/usr/bin/env python3

import argparse
import json
import sys
import os

root_dir = os.path.abspath(os.path.join(sys.path[0], '../../'))
sys.path.insert(0, root_dir)

from bluesky import models

EXAMPLES_STRING = """
Examples:

    {script} -i output.json

 """.format(script=sys.argv[0])
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--input', help="bsp output file", required=True)
    parser.epilog = EXAMPLES_STRING
    parser.formatter_class = argparse.RawTextHelpFormatter
    return parser.parse_args()

def count(input_data):
    fires = input_data.pop('fires', None) or input_data.pop('fire_information', [])
    num_locations = sum([len(models.fires.Fire(f).locations) for f in fires])
    print("Fires: {}".format(len(fires)))
    print("Locations: {}".format(num_locations))

def main():
    args = parse_args()

    with open(args.input, 'r') as f:
        input_data = json.loads(f.read())

    count(input_data)


if __name__ == "__main__":
    main()
