#!/usr/bin/env python3

__author__ = "Joel Dubowy"

import argparse
import logging
import os
import re
import subprocess
import sys
import traceback

try:
    from bluesky import  __version__
except:
    root_dir = os.path.abspath(os.path.join(sys.path[0], '../../../'))
    sys.path.insert(0, root_dir)
    from bluesky import __version__


EXAMPLES_STR = """
Examples:
  $ ./dev/scripts/docker/build-docker-image.py
  $ ./dev/scripts/docker/build-docker-image.py
 """

REPO_ROOT_DIR = os.path.abspath(os.path.join(__file__, '../../../..'))

FINAL_INSTRUCTIONS = """
    To upload:
""".format(version=__version__)

def exit_with_msg(msg, exit_code=1):
    """Prints message and exits
    """
    sys.stderr.write("\n%s\n\n" % (msg))
    sys.exit(exit_code)

def parse_args():
    parser = argparse.ArgumentParser()
    # TODO: add option to specify version, to avoid prompt ?
    # TODO: add option to upload to docker hub, to avoid prompt ?
    # TODO: add back option to override image name to use instead of 'bluesky' ?
    #    (This option was removed because I never used it)
    parser.epilog = EXAMPLES_STR
    parser.formatter_class = argparse.RawTextHelpFormatter
    return parser.parse_args()


def _call(cmd_args):
    sys.stdout.write("Calling '{}'\n".format(' '.join(cmd_args)))
    r = subprocess.call(cmd_args)
    if r:
        msg = "Command '{}' returned error code {}".format(' '.join(cmd_args), r)
        exit_with_msg(msg, exit_code=r)

def build():
    dockerfile_pathname = os.path.join(REPO_ROOT_DIR, 'Dockerfile')
    _call(['docker','build', '-t', 'bluesky', REPO_ROOT_DIR])

def tag():
    tag_version = None
    while not tag_version or not re.compile('^v\d+\.\d+\.\d+$').match(tag_version):
        if tag_version:
            sys.stdout.write("Enter a tag version of the form 'v{}' or press"
                " enter to use the default\n".format(__version__))
        sys.stdout.write('Tag version [v{}]: '.format(__version__))
        tag_version = input().strip() or 'v' + __version__
    _call(['docker', 'tag', 'bluesky', 'pnwairfire/bluesky:latest'])
    _call(['docker', 'tag', 'bluesky', 'pnwairfire/bluesky:' + tag_version])
    return tag_version

def upload(tag_version):
    sys.stdout.write('Upload to hub.docker.com?: [y/N]: ')
    r = input().strip()
    if r and r.lower() in ('y', 'yes'):
        sys.stdout.write("Pushing to docker hub.\n")
        _call(['docker', 'login'])
        _call(['docker', 'push', 'pnwairfire/bluesky:latest'])
        _call(['docker', 'push', 'pnwairfire/bluesky:' + tag_version])
    sys.stdout.write('Logout of hub.docker.com?: [Y/n]: ')
    r = input().strip()
    if not (r and r.lower() in ('n', 'no')):
        _call(['docker', 'login'])

if __name__ == "__main__":
    args = parse_args()
    build()
    tag_version = tag()
    upload(tag_version)
