#!/usr/bin/env bash

# remove all stopped containers
docker ps -a | awk 'NR > 1 {print $1}' | xargs docker rm

# remove all untagged images:
docker images | grep "<none>" | awk '{print $3}' | xargs docker rmi
