#!/usr/bin/env bash

docker run --rm -ti \
       -v $HOME/code/:/code/ \
       -v $HOME/NAM84/:/NAM84/ \
       -v $HOME/DRI_6km/:/DRI_6km/  \
       -v $HOME/docker-bsp-output/:/bsp-output/ \
       -e PYTHONPATH=/code/pnwairfire-bluesky/ \
       -e PATH=/code/pnwairfire-bluesky/bin/:$PATH \
       -w /code/pnwairfire-bluesky/ \
       bluesky bash

