#!/usr/bin/env bash

docker run --rm -ti \
       -v $HOME/code/:/code/ \
       -v $HOME/Met/NAM/12km/ARL/:/data/Met/NAM/12km/ARL/ \
       -v $HOME/Met/CANSAC/6km/ARL/:/data/Met/CANSAC/6km/ARL/  \
       -v $HOME/docker-bsp-output/:/bsp-output/ \
       -e PYTHONPATH=/code/pnwairfire-bluesky/ \
       -e PATH=/code/pnwairfire-bluesky/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
       -w /code/pnwairfire-bluesky/ \
       bluesky bash
