#!/usr/bin/env python

__author__ = "Joel Dubowy"

import json
import logging
import os
import subprocess
import sys
import tempfile
import traceback

import afscripting

REQUIRED_ARGS = [
    {
        'short': '-i',
        'long': '--input-file',
        'dest': 'input_files',
        'help': 'input file(s) containing JSON formatted fire data',
        'action': "append",
        'default': []
    },
    {
        'short': '-r',
        'long': '--repo-root',
        'help': "path to repo root"
    },
    {
        'short': '-m',
        'long': '--module',
        'dest': 'modules',
        'help': 'module to run',
        'action': 'append',
        'default': []
    }
]

OPTIONAL_ARGS = [
    {
        'short': '-p',
        'long': '--pretty-format',
        'help': "format json output",
        'action': 'store_true'
    },
    {
        'short': '-d',
        'long': '--mount-dir',
        'dest': 'mount_dirs',
        'help': "extra directories to mount in container",
        'action': 'append',
        'default': []
    }
    # TODO: add --met-dir (to mount)
]


EXAMPLES_STR = """This script updates the arl index with the availability of
a particular domain on the current server.

Examples:
  $ ./dev/scripts/docker/run-in-docker.py \\
      -i /path/to/fire.json \\
      -c /path/to/config.json \\
      -r /path/to/bluesky/repo/ \\
      -d /path/to/met/:/met/ \\
      -d /path/to/output/dir/ \\
      -m fuelbeds -m consumption -m emissions \\
      -m timeprofile -m findmetdata -m localmet \\


Note about volumes and mounting: mounting directories outside of your home
directory seems to result in the directories appearing empty in the
docker container. Whether this is by design or not, you apparently need to
mount directories under your home directory.  Sym links don't mount either, so
you have to cp or mv directories under your home dir in order to mount them.
 """


if __name__ == "__main__":
    parser, args = afscripting.args.parse_args(REQUIRED_ARGS, OPTIONAL_ARGS,
        epilog=EXAMPLES_STR)

    # TODO: if repo root is in args.input_file, replace it with ''

    try:
        input_files = [os.path.abspath(i) for i in args.input_files]
        config_file = None
        if args.config_file_options or args.config_options:
            config = {"config": {}}
            if args.config_file_options:
                config["config"].update(args.config_file_options)
            if args.config_options:
                config["config"].update(args.config_options)
            f = tempfile.NamedTemporaryFile(delete=False)
            f.write(json.dumps(config).encode())
            f.close()
            config_file = f.name

        cmd_args = [
            'docker', 'run', '--rm', '-i',
            '-v', '{}:/bluesky-repo/'.format(args.repo_root),
            '-w', '/bluesky-repo/',
            '-e', 'PYTHONPATH=/bluesky-repo/',
            '-e', 'PATH=/bluesky-repo/bin/:$PATH'
        ]
        for i in input_files:
            cmd_args.extend([
                '-v', '{f}:{f}'.format(f=i),
            ])
        if config_file:
            cmd_args.extend([
                '-v', '{f}:{f}'.format(f=config_file),
            ])

        for d in args.mount_dirs:
            dirs = d.split(':')
            h, c = (dirs[0], dirs[1]) if len(dirs) == 2 else (dirs, dirs)
            cmd_args.extend([
                '-v', '{}:{}'.format(h, c)
            ])

        cmd_args.extend([
            'bluesky',
            './bin/bsp',
            '--log-level', logging.getLevelName(args.log_level)
        ])
        for i in input_files:
            cmd_args.extend([
                '-i', '{f}'.format(f=i),
            ])
        if config_file:
            cmd_args.extend([
                '--config-file', '{f}'.format(f=config_file),
            ])

        cmd_args.extend(args.modules)
        if args.pretty_format:
            cmd_args.extend(['|', 'python', '-m', 'json.tool'])
        cmd = ' '.join(cmd_args)
        logging.debug('Command: {}'.format(cmd))
        # Note: there are security vulnerabilitys with using shell=True,
        #  but it's not an issue for a test script like this
        subprocess.call(cmd, shell=True)

    except Exception as e:
        logging.error(e)
        logging.debug(traceback.format_exc())
        afscripting.utils.exit_with_msg(e)
